### ISSUE TITLE
Gestion du referentiel

### ISSUE THREAD

**Issue by vinsag** [IGNF/geoportal-wfs-client#17]
Suivant le référentiel utilisé en entrée, nous ne devons pas inverser les coordonnées en entrée pour la recherche

**Comment by mborne** [comment]
Oui... Pour clarifier, si j'ai bien tout compris :

* La géométrie encodée dans cql_filter doit être dans la même projection que la source de données
* Quand la projection de la source de données est EPSG:4326, GeoServer interprète EPSG:4326 comme du lat,lon (contrairement à CRS:84 où c'est du lon,lat)
* Visiblement, pour EPSG:3857, GeoServer interprète en X,Y
