### ISSUE TITLE
Add ssl option

### ISSUE THREAD

**Issue by cyrilchapon** [IGNF/geoportal-wfs-client#2]
Just like in https://github.com/IGNF/geoportal-access-lib, we need an ssl option as browsers block `http` ajax calls from `https` context, this make the lib unusable in most client side contexts.

Temporary workaround :

**ES6**

```
import GpWfsClient from 'geoportal-wfs-client'
import { omit, isUndefined } from 'lodash'

class ImprovedGpWfsClient extends GpWfsClient {
  constructor(apiKey, options) {
    super(apiKey, omit(options, 'ssl'))

    this.ssl = options ? (isUndefined(options.ssl) ? true : !!options.ssl) : true
    this.getUrl = this.getUrl.bind(this)
  }

  getUrl() {
    return `http${this.ssl ? 's' : ''}://wxs.ign.fr/${this.apiKey}/geoportail/wfs`
  }
}

export default ImprovedGpWfsClient

```

**Comment by mborne** [comment]
Thanks for you're feedback. Any objection if I had an option `url` with the following default value  : 

https://wxs.ign.fr/{apiKey}/geoportail/wfs

?

This should fix you're problem and allow the reuse of the client for different WFS servers (this one in particular : https://github.com/IGNF/geoportail-urbanisme-dev#flux-wfs )

**Comment by cyrilchapon** [comment]
Hey @mborne 

As long as use of ssl (which is ok for browser, but remains prohibitive for some environments where ssl wouldn't be supported) is not enforced (ie. your url is overridable), this seems to be ok :)

**Comment by floriancerizay** [comment]
Hi @cyrilchapon 
This issue should be fixed with the last commit on master
We added an "url" option with "https://wxs.ign.fr/{apiKey}/geoportail/wfs" as default value

```
var Client = function(options){
    // should be removed to allow user/password?
    if (typeof options.apiKey === 'undefined' ) throw new Error('Required param: apiKey');
    this.url = options.url || 'https://wxs.ign.fr/{apiKey}/geoportail/wfs';
    this.apiKey = options.apiKey || null;
    this.headers = options.headers || {};    
};

/**
 * Get WFS URL
 */
Client.prototype.getUrl = function(){
    return this.url.replace('{apiKey}', this.apiKey);
};
```
