### ISSUE TITLE
fix travis tests and AXIOS issue for https behind http proxy

### ISSUE THREAD

**Issue by mborne** [IGNF/geoportal-wfs-client#5]
* #10 - Travis test where crashed (expired key)
* Local testing fails for https (seems to be an axios issue : https://github.com/axios/axios/issues/925)

**Comment by mborne** [comment]
@floriancerizay see branch issue_5 
Please adapt tests to check both http and https (local hebind proxy, then travis throw pull request)

**Comment by mborne** [comment]
Test adapted using http instead of https. Still waiting for axios fix to be merged.

**Comment by vinsag** [comment]
A patch includes on 0.19.0-beta.1(axios issue for more details :`https://github.com/axios/axios/issues/925)

**Comment by mborne** [comment]
Axios issue fixed using `https-proxy-agent` and `http-proxy-agent` (see `internal/httpClient`)

```bash
export HTTP_PROXY=http://proxy:3128
export HTTPS_PROXY=http://proxy:3128

GEOPORTAL_WFS_URL=http://wxs.ign.fr/{apiKey}/geoportail/wfs npm run test
# https://wxs.ign.fr/{apiKey}/geoportail/wfs is the default
npm run test
```
